version: "3.8"

services:
  backend:
    image: raon98/accompany_mobile:backend
    build:
      context: ./backend
    ports:
      - "8090:8090"
    depends_on:
      - database
    environment:
      - LANG=C.UTF-8
    networks:
      - my_network
    env_file:
      - .env

  frontend:
    image: raon98/accompany_mobile:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile_dev
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
        - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true
    networks:
      - my_network
    env_file:
      - .env


  database:
    image: raon98/accompany_mobile:database
    build:
      context: ./backend
      dockerfile: Dockerfile_DB
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - my_network
    volumes:
      - database_data:/var/lib/mysql
    env_file:
      - .env

networks:
  my_network:
    driver: bridge

volumes:
  database_data:
