version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8090:8090"
    depends_on:
      - database
    environment:
      - LANG=C.UTF-8
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8090/v1/
    depends_on:
      - backend
    networks:
      - my_network

  database:
    build:
      context: ./backend
      dockerfile: Dockerfile_DB
    restart: always
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
