version: "3.8"

services:
  backend:
    image: raon98/accompany_mobile:backend
    build:
      context: ./backend
    ports:
      - "8090:8090"
    depends_on:
      - database
    environment:
      - LANG=C.UTF-8
    networks:
      - my_network

  frontend:
    image: raon98/accompany_mobile:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  database:
    image: raon98/accompany_mobile:database
    build:
      context: ./backend
      dockerfile: Dockerfile_DB
    restart: always
    ports:
      - "3307:3306"
    networks:
      - my_network
    volumes:
      - database_data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  database_data:
