version: "3.8"

services:
  backend:
    image: raon98/accompany_mobile:backend
    build:
      context: ./backend
    ports:
      - "8090:8090"
    environment:
      - LANG=C.UTF-8
    networks:
      - my_network
    env_file:
      - .env

  frontend:
    image: raon98/accompany_mobile:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile_dev
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
        - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true
    networks:
      - my_network
    env_file:
      - .env

networks:
  my_network:
    driver: bridge

