# Node 버전 20을 기반으로 하는 이미지 사용
FROM node:20 AS dev

WORKDIR /usr/src/app

COPY .npmrc ./.npmrc

COPY package.json ./

RUN npm install

#COPY ./ ./

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
RUN echo "REACT_APP_BACKEND_URL: $REACT_APP_BACKEND_URL"

ENV CHOKIDAR_USEPOLLING=true
COPY ./script/start.sh /usr/src/app/start.sh
RUN chmod +x /usr/src/app/start.sh

CMD ["./start.sh"]
