name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          REACT_APP_BACKEND_AXIOS_URL: ${{ secrets.REACT_APP_BACKEND_AXIOS_URL }}
          OCR_VISION_KEY: ${{ secrets.OCR_VISION_KEY }}
          CORE_ALLOWED_ORIGIN: ${{ secrets.CORE_ALLOWED_ORIGIN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker-compose -f docker-compose-mobile.yaml build
          echo "dckr_pat_Vd5Hf1l2q0FV6mCntuSCjoP6r74" | docker login -u "raon98" --password-stdin 
          docker-compose -f docker-compose-mobile.yaml push

      - name: Deploy
        run: |
          docker-compose -f docker-compose-mobile.yaml up
