name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        run: |
          cat .env
          docker-compose -f docker-compose-mobile.yaml build
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${secrets.DOCKER_USERNAME}" --password-stdin 
          docker-compose -f docker-compose-mobile.yaml push
