- name: Build and push Docker images
  env:
    MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
    MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
    REACT_APP_BACKEND_AXIOS_URL: ${{ secrets.REACT_APP_BACKEND_AXIOS_URL }}
    OCR_VISION_KEY: ${{ secrets.OCR_VISION_KEY }}
    CORE_ALLOWED_ORIGIN: ${{ secrets.CORE_ALLOWED_ORIGIN }}
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  run: |
    cat .env
    docker-compose -f docker-compose-mobile.yaml build
    echo "${secrets.DOCKER_USERNAME}" | docker login -u "${secrets.DOCKERHUB_TOKEN}" --password-stdin 
    docker-compose -f docker-compose-mobile.yaml push
