name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Display Secrets
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build and push Docker images
        run: |
          cat .env
          docker-compose -f docker-compose-mobile.yaml build
         echo "dckr_pat_Vd5Hf1l2q0FV6mCntuSCjoP6r74" | docker login -u "raon98" --password-stdin
          docker-compose -f docker-compose-mobile.yaml push
